# Site settings
title: BIGBALLON

description:
  en: "This is Wei Li's personal website, the style of this website is borrowed from Hexiang(Frank) Hu's."
  cn: "这是李韡的个人主页，用于分享他的个人经历，项目，学术论文，技术相关/不相关的博客。"
keywords:
  en: "Wei Li,BIGBALLON,Posts,Artificial Intelligence,Deep Learning,Reinforcement Learning"
  cn: "李韡,博客,人工智能,深度学习,强化学习"
background: /images/background/background-cube.jpg
deep_background: /images/background/background-deepcube-2.jpg

baseurl: ""
# the subpath of your site, e.g. /blog/
url: "https://bigballon.github.io"
# the base hostname & protocol for your sit

# Paginationœ
paginate: 10
paginate_path: "/posts/page/:num/"

# Build settings
markdown: kramdown

# permalink setting
# permalink: pretty

permalink: /posts/:title.html

# highlighter: rouge
highlighter: rouge


# Social media link for the site
social:
  github:     bigballon
  facebook:   fm.bigballon
  wechat:     bigballon
  rss:        /feed.xml

# google_analytics_token: "UA-60071442-1"
# google_tags_token: "GTM-K5ZTMW"

disqus: BIGBALLON

# customized document resources
collections:
  projects:
    output: true

scss:
  sass_dir: _scss
  style: :compressed

plugins: [jekyll-paginate]

plugins_dir:
  ['jekyll-paginate', 'jekyll/scholar', 'jekyll-sitemap']
